name: pick_pic
description: a project about puzzle

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
# https://pub.dev/packages/camera#-installing-tab-
  camera: ^0.8.1+2
  path_provider:
  path: ^1.8.2
# Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^1.12.0
# Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^9.1.0
  firebase_storage: ^10.2.7

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^3.3.7
# https://pub.dev/packages/cloud_firestore#-installing-tab-
  cloud_firestore: ^2.1.0 
  google_sign_in: ^5.2.3
# https://pub.flutter-io.cn/packages/image_picker#-installing-tab-
  image_cropper: ^1.4.0
  image: ^3.0.2
  # https://pub.dev/packages/flutter_image_compress#why-dont-you-use-dart-to-do-it
  flutter_image_compress: ^1.0.0
# https://pub.dev/packages/random_string#-installing-tab-
  random_string: ^2.2.0-nullsafety
# https://flutter.dev/docs/cookbook/persistence/sqlite
#  sqflite: ^2.0.0+3
# https://pub:dev/packages/stop_watch_timer:
  stop_watch_timer: ^1.2.0+1
# https://pub:dev/packages/vibration:
  vibration: ^1.7.4-nullsafety.0
# https://pub.dev/packages/fab_circular_menu
  fab_circular_menu: ^1.0.2
  http: ^0.13.3
  waterfall_flow: any
## https://pub.dev/packages/animations#-installing-tab-
#  animations:
# https://pub.dev/packages/provider#-installing-tab-
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.1.0
# https://github.com/passsy/dart-lint
  pedantic: ^1.11.0
#  https://pub:dev/packages/flutter_svg/install:
  flutter_svg: ^0.22.0
#  flutter_spinkit: ^4.1.2
  cached_network_image: ^3.0.0
#  https://github.com/flutterchina/dio/blob/master/README-ZH.md
  dio: ^5.0.3
  #  https://pub.dev/packages/mockito/install
  mockito: ^5.3.0
  cloud_firestore_mocks: ^0.9.0+1
  firebase_auth_mocks: ^0.8.2
  google_sign_in_mocks: ^0.2.1
#  firebase_messaging: ^10.0.2
  flutter_local_notifications: ^6.0.0
#  use with notification
  rxdart: ^0.27.1
#  https://pub.dev/packages/moor/install
  moor:
  sqlite3_flutter_libs:
#  https://flutter.cn/docs/cookbook/testing/unit/introduction
  test: ^1.22.0


  image_picker: ^0.8.4+8
  firebase: ^9.0.2

dev_dependencies:
  # https://pub.dev/packages/floor
  floor_generator: ^1.3.0
  build_runner: ^2.1.11
  freezed: ^2.1.0+1
  flutter_launcher_icons: ^0.9.0
  moor_generator:
# over
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/puzzle_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/bg/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - resources/test/get_success_response.json

  generate: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages