// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM2Ka9INqxuvkrKUpTl91d4yh6p9eGaRQ',
    appId: '1:301008876836:web:498c3cc8e800139b39afb1',
    messagingSenderId: '301008876836',
    projectId: 'pick-pic-540a9',
    authDomain: 'pick-pic-540a9.firebaseapp.com',
    storageBucket: 'pick-pic-540a9.appspot.com',
    measurementId: 'G-QSZBDLDF0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvabAP8PTbbQX5LVGLm_ThfosMjtubEsg',
    appId: '1:301008876836:android:0529c43d0e26207639afb1',
    messagingSenderId: '301008876836',
    projectId: 'pick-pic-540a9',
    storageBucket: 'pick-pic-540a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7llUPF6gJiIqFi6FYPhF3r9CEQ64_zeg',
    appId: '1:301008876836:ios:09e8f7fc851a4dd539afb1',
    messagingSenderId: '301008876836',
    projectId: 'pick-pic-540a9',
    storageBucket: 'pick-pic-540a9.appspot.com',
    iosClientId:
        '301008876836-ovrp7u03ov2heen0u1al9jjq9uo2oud1.apps.googleusercontent.com',
    iosBundleId: 'com.example.pick',
  );
}
