// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkR3IxMRL4oCkewywGtvz0TNto6-MSW-8',
    appId: '1:826146684437:web:2b9201b550905081c8d81c',
    messagingSenderId: '826146684437',
    projectId: 'pick-pic-puzzle',
    authDomain: 'pick-pic-puzzle.firebaseapp.com',
    databaseURL: 'https://pick-pic-puzzle-default-rtdb.firebaseio.com',
    storageBucket: 'pick-pic-puzzle.appspot.com',
    measurementId: 'G-SH5Q2J9ZT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_HNBtgfozfjAiJ3JhlKji1OySUcyaZs8',
    appId: '1:826146684437:android:a2eb907b52946f26c8d81c',
    messagingSenderId: '826146684437',
    projectId: 'pick-pic-puzzle',
    databaseURL: 'https://pick-pic-puzzle-default-rtdb.firebaseio.com',
    storageBucket: 'pick-pic-puzzle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4SUM_l8FsSELWNCC2FVkDDFdeskalho',
    appId: '1:826146684437:ios:4955d0a1540f1e47c8d81c',
    messagingSenderId: '826146684437',
    projectId: 'pick-pic-puzzle',
    databaseURL: 'https://pick-pic-puzzle-default-rtdb.firebaseio.com',
    storageBucket: 'pick-pic-puzzle.appspot.com',
    iosClientId: '826146684437-sa19835qlnb55t7024jaob4i0arvrpm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pick',
  );
}
